apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: kube-sandbox
spec:
  containers:
  - image: bitnami/nginx:1.20
    name: nginx
  - image: ubuntu:20.04
    name: ubuntu
    command: ["/bin/bash"]
    args: ["-c", "while true; do sleep 300; done"]
