apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  namespace: kube-sandbox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: bitnami/nginx:1.20
