apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: items.fedyanov.com
spec:
  group: fedyanov.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                itemName:
                  type: string
                itemDescription:
                  type: string
                itemScore:
                  type: string
  scope: Namespaced
  names:
    plural: items
    singular: item
    kind: Item
    shortNames:
      - itm


