apiVersion: v1
kind: ConfigMap
metadata: 
    name: {{ .Release.Name }}-configmap
data:
    myvalye: "Hello World! from Release object: {{ .Release }} Chart object: {{ .Chart.Name }}-{{ .Chart.Version }} Template: {{ .Template }}"