apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: bitnami/nginx:1.20
          env:
            - name: key_local
              value: data_local
            - name: key1
              valueFrom:
                configMapKeyRef:
                  name: appconfig
                  key: key1
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: config-volume
              mountPath: /etc/config.txt
              subPath: config.txt
      volumes:
        - name: config-volume
          configMap:
            name: appconfig
