apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-dp
  labels:
    env: "prod"
  annotations:
    prometheus.io/scrape: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotas
  template:
    metadata:
      labels:
        app: quotas
    spec:
      containers:
        - name: memcached
          image: memcached:latest
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
        - name: redis
          image: redis:latest
          resources:
            limits:
              cpu: 300m
              memory: 300Mi
            requests:
              cpu: 300m
              memory: 300Mi

