apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-fs
  labels:
    env: "prod"
  annotations:
    prometheus.io/scrape: "true"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi

