apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-test
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: curl-rebrainme
        spec:
          restartPolicy: OnFailure
          containers:
          - name: main
            image: alpine
            command: ["curl https://lk.rebrainme.com/kubernetes/report"]
            # args: ["-c","4","8.8.8.8"]
